# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 10:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('aid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('DOD', models.DateField(blank=True, null=True)),
                ('bio', models.TextField()),
                ('pic', models.ImageField(upload_to='static/images/')),
                ('followAuthor', models.ManyToManyField(related_name='FollowAuthor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('desc', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='static/images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookcity.Author')),
                ('readBooks', models.ManyToManyField(related_name='ReadBook', to=settings.AUTH_USER_MODEL)),
                ('wishListBoos', models.ManyToManyField(related_name='Wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('bookCategory', models.ManyToManyField(related_name='BookCategory', to='bookcity.Book')),
                ('likeCategory', models.ManyToManyField(related_name='UserCategory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookcity.Book')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
