# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='pic',
            field=models.ImageField(upload_to='/home/MohamedSaeed/BookCity/static/images/'),
        ),
    ]
