# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcity', '0006_auto_20180227_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(),
        ),
    ]
